name: mangues_da_amazonia
description: App ManguesDaAmazonia

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_rotation: ^2.0.0
  sqflite: ^2.0.0+4
  flutter_mobx: ^2.0.2
  mobx: ^2.0.0
  mobx_codegen: ^2.0.0
  url_launcher: ^6.0.0-nullsafety.1
  video_player: ^2.2.7
  video_player_platform_interface: ^4.2.0
  youtube_player_flutter: ^8.0.0
  video_player_360: ^0.1.5
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  path_provider: ^2.0.8
  flutter_svg: ^1.0.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - som_error.mp3
    - som_acerto.mp3
    - fase1.mp3
    - fase2.mp3
    - fase3.mp3
    - boia.png
    - bola.png
    - bota.png
    - capacete.png
    - carrinhobb.png
    - escudo.png
    - guardachuva.png
    - jeans.png
    - manopla.png
    - martelo.png
    - mochila.png
    - motor.png
    - nave.png
    - pet.png
    - satelite.png
    - boia-p_b.png
    - bola-p_b.png
    - bota-p_b.png
    - capacete-p_b.png
    - carrinhobb-p_b.png
    - escudo-p_b.png
    - guardachuva-p_b.png
    - jeans-p_b.png
    - manopla-p_b.png
    - martelo-p_b.png
    - mochila-p_b.png
    - motor-p_b.png
    - nave-p_b.png
    - pet-p_b.png
    - satelite-p_b.png
    - layout_certificado.png
    - ic_mangues.png
    - fundo_mangue_vermelho.jpeg
    - fundo_mangue_preto.jpeg
    - gameover.mp3
    - intro_.mp4
    - botao_audio_ativo.png
    - ic_mangues.png
    - logo_petrobras.png
    - logo_preferencial.png
    - logo_horizontal_preferencial.png
    - img_app.jpg
    - botao_opcao.png
    - botao_audio.png
    - botao_jogar.png
    - mapa_vermelho.png
    - arvore_1.png
    - arvore_2.png
    - arvore_3.png
    - lixo_sombrinha.png
    - lixo_cadeira.png
    - lixo_garrafa.png
    - lixo_pneu.png
    - lixo_caixa.png
    - lixo_caixa_bloqueada.png
    - lixo_garrafa_bloqueada.png
    - lixo_pneu_bloqueada.png
    - lixo_somb_bloqueado.png
    - lixo_cadeira_bloqueada.png
    - carangueijo.png
    - garca_questoes.png
    - logo_mangue.jpeg
    - pop_acerto.png
    - voce_errou.png
    - link_360.png
    - botao_pular.png
    - cenario_tralhoto.jpg
    - garca_e_carangueijo.png
    - tralhoto.png
    - mapa_completo.png
    - mao_pelada.png
    - garca_triste.png
    - garca_feliz.png
    - cadeado_aberto.png
    - cadeado_fechado.png
    - arvore_4.png
    - arvore_falando.png
    - placa_mangue_vermelho.png
    - placa_mangue_preto.png
    - placa_mangue_branco.png
    - caixa_dialogo.png
    - placa_mangue_vermelho_map.png
    - a_alternativa_normal.png
    - a_alternativa_certa.png
    - a_alternativa_errada.png
    - b_alternativa_errada.png
    - b_alternativa_certa.png
    - b_alternativa_normal.png
    - c_alternativa_certa.png
    - c_alternativa_errada.png
    - c_alternativa_normal.png
    - d_alternativa_certa.png
    - d_alternativa_errada.png
    - d_alternativa_normal.png
    - caixa_pergunta.png
    - limpou_vermelho.png
    - limpou_preto.png
    - limpou_branco.png
    - placa_intro.png
    - seta.png
    - seta_2.png
    - placa_mangue_preto_map.png
    - loading.png
    - placa_mangue_branco_map.png
    - selo.png
    - mangue_semi_desbloqueado.jpg
    - carangueijo_conversando.png
    - guaxinim_feliz.png
    - logo_mangues.svg
    - fundo_mangue_branco.jpeg
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MochiyPopPOne
      fonts:
        - asset: lib/assets/Fonts/Mochiy_Pop_P_One/MochiyPopPOne-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: lib/assets/Fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: lib/assets/Fonts/Ubuntu/Ubuntu-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
