name: mangues_da_amazonia
description: App ManguesDaAmazonia

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_rotation: ^2.0.0
  sqflite: ^2.0.0+4
  flutter_mobx: ^2.0.2
  mobx: ^2.0.0
  mobx_codegen: ^2.0.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img_app.jpg
    - tela_01.jpg
    - tela_03.jpg
    - tela_04.jpg
    - tela_06.png
    - tela_05.png
    - tela_08.jpg
    - tela_12.jpg
    - tela_14.jpg
    - botao_opcao.png
    - botao_audio.png
    - botao_jogar.png
    - mapa_vermelho.png
    - arvore_1.png
    - arvore_2.png
    - arvore_3.png
    - lixo_sombrinha.png
    - lixo_cadeira.png
    - lixo_garrafa.png
    - lixo_pneu.png
    - lixo_caixa.png
    - lixo_caixa_bloqueada.png
    - lixo_garrafa_bloqueada.png
    - lixo_pneu_bloqueada.png
    - lixo_somb_bloqueado.png
    - lixo_cadeira_bloqueada.png
    - mangue_01_vermelho.jpg
    - carangueijo.png
    - balao_carangueijo.png
    - fundo_mangue_vermelho.jpg
    - garca_questoes.png
    - balao_empty.png
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MochiyPopPOne
      fonts:
        - asset: lib/assets/Fonts/Mochiy_Pop_P_One/MochiyPopPOne-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
